<template>
  <div>
    <TitledLinkButtons :title="title" :links="transcriptLinkButtons" />
    <p class="text-sm bg-n-400 p-4">Note that these transcripts are not official and may contain errors. They are generated by Google's Text to Speech API.</p>
  </div>
</template>

<script setup lang="ts">
import type { BasicTranscriptListItem } from '~/model/transcript/BasicTranscript';
import type { TitledLinkButton } from '~/components/TitledLinkButtons.vue';

const fb = useFirebase();
const transcriptLinkButtons = ref<Array<TitledLinkButton>>([]);
const title = 'Transcripts';

useSeoMeta({
  title: 'Stargirlology',
  description: 'Stargirl Transcripts',
});


fb.inClient(async ({ modDb }) => {
  const ref = modDb.ref(modDb.getDatabase(), DbPath.transcriptList());

  modDb.onValue(ref, (snapshot) => {
    const list = snapshot.val() as Record<string, BasicTranscriptListItem>;
    transcriptLinkButtons.value = [];

    const transcriptList = Object.entries(list || {})
      .map(([, value]) => value )
      .sort((a, b) => a.episodeNumber - b.episodeNumber);

    transcriptList.forEach((transcript) => {
      const title = `${transcript.episodeNumber} - ${transcript.episodeTitle}`;
      const to = `/transcripts/${transcript.episodeNumber}-${transcript.episodeTitle}`;
      if (transcriptLinkButtons.value.find((button) => button.title === title)) return;
      transcriptLinkButtons.value.push({ to, title });
    });
  });
});
</script>
